const ShopActionTypes = {
<<<<<<< HEAD
    FETCH_COLLECTIONS_START: "FETCH_COLLECTIONS_STARTS",
    FETCH_COLLECTIONS_SUCCESS: "FETCH_COLLECTIONS_SUCCESS",
    FETCH_COLLECTIONS_FAILUE: "FETCH_COLLECTIONS_FAILUE",
=======
    UPDATE_COLLECTIONS: "UPDATE_COLLECTIONS",
>>>>>>> 19f24ff57529e762440612cd0b0213be1b6aa8ef
};

export default ShopActionTypes;